---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
    run_list: ['recipe[apt]', 'recipe[geminabox]']
    attributes:
      geminabox:
        ssl:
          enabled: true
        unicorn:
          exec: "/opt/chef/embedded/bin/unicorn"
        nginx:
          bind: "*"
